### ISSUE TITLE
使用编译过的jbr环境，出现markdown插件无法使用的问题

### ISSUE THREAD

**Issue by Sud0x67** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#1]
已经使用了编译过的最新版本，但pycharm的markdown插件无法使用

**Comment by RikudouPatrickstar** [comment]
https://pan.baidu.com/s/1hkX9Gi2xtBIqV6zgNSIugA
密码 am14

试试这个别人备份的去年编译的版本。已经放弃使用 Linux 桌面端很久了，最后一次使用的时候好像确实是有这个问题。

**Comment by Sud0x67** [comment]
感谢，试了一下还是不行，不过依然很感谢 :+1:

**Comment by RikudouPatrickstar** [comment]
最新的 release 解决了这个问题

**Comment by Sud0x67** [comment]
简单测试了一下，markdown可以预览了，感谢
