### ISSUE TITLE
idea中打开文件会holding几秒，然后才可以执行搜索等操作

### ISSUE THREAD

**Issue by feiyuyitiao** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#11]
如题：
采用jbr后，idea中打开文件，会holding几秒； 
**现象**：执行快捷键ctrl+F搜索、ctrl+W关闭，不起作用。
等待一会儿才可以操作；
已打开文件不受影响。
替换回原来jbr，重启idea后无此问题。

IntelliJ IDEA 2021.1.3 (Ultimate Edition)
Build #IU-211.7628.21, built on June 30, 2021
Licensed to IntelliJ IDEA Evaluator
Expiration date: March 16, 2022
Runtime version: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.83-amd64-desktop
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: documentation.show.toolbar=true
Non-Bundled Plugins: IdeaVIM (1.9.2), io.zhile.research.ide-eval-resetter (2.1.6), org.jetbrains.plugins.go-template (211.6693.44), name.kropp.intellij.makefile (211.7628.1), com.intellij.kubernetes (211.7442.27), nb-mind-map-idea (1.5.0), org.intellij.scala (2021.1.22), com.jetbrains.php (211.7628.25), Pythonid (211.7628.24), org.jetbrains.plugins.go (211.7628.1)
Kotlin: 211-1.4.32-release-IJ7628.19
Current Desktop: Deepin

**Comment by RikudouPatrickstar** [comment]
https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/releases/tag/202110301849

用这个也有问题吗？

**Comment by EXing** [comment]
+1

**Comment by feiyuyitiao** [comment]
> https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/releases/tag/202110301849
> 
> 用这个也有问题吗？

体验了以下暂时没有发现问题，感谢！

**Comment by RikudouPatrickstar** [comment]
pre release 我都没有测试的，而且每次出的包都是自动用最新的代码编译的，并不能保证稳定。所以。。。不是特别有必要的话，不建议使用 pre release 的包。
