### ISSUE TITLE
Manjaro fcitx5 pycharm2021.3.3输入法仍然不在光标

### ISSUE THREAD

**Issue by atlasju** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#13]
rider 2021.3.4也是一样，无论使用最新还是正是release情况就和使用自带的jrb效果一样，没有解决这个问题。
其实后来我自己编译了一遍也是一样的情况

**Comment by RikudouPatrickstar** [comment]
桌面环境也是gnome4*吗？

**Comment by RikudouPatrickstar** [comment]
`manjaro, fctix5.0.15, gnome`环境，使用`fcitx5-chinese-addons`输入法，无法复现，你换最新的正式release试试
