### ISSUE TITLE
Ubuntu22.10无法解决光标不跟随的问题

### ISSUE THREAD

**Issue by stay-foolish-forever** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#14]
本人使用的是Ubuntu22.10，桌面环境为Gnome40，输入法为fcitx5，目前替换掉jbr之后依然无法解决光标不跟随的问题

**Comment by stay-foolish-forever** [comment]
抱歉系统版本写错了，是21.10，我同时测试了IDEA2022.1和IDEA2021.3两个版本，都出现光标不跟随的情况

**Comment by RikudouPatrickstar** [comment]
更老的 2021.2 2021.1 有这个问题吗？上个issue也提到了这个问题，还没时间看

**Comment by zyf0330** [comment]
Ubuntu 21.10 KDE、 WebStorm 2021.3 和 2022.1 没问题

**Comment by RikudouPatrickstar** [comment]
暂且怀疑是gnome4*的问题，还没仔细看。我刚刚在edge用ibus，输入框居然也在左下角

**Comment by RikudouPatrickstar** [comment]
你们 fcitx5 都用的啥中文输入法，我下次试试。刚刚装了下几个国产输入法，依赖都是 fcitx4；fcitx5 调半天愣是没按出中文来，也可能是因为上的 Ubuntu jammy 碰上bug了

**Comment by Voghost** [comment]
刚刚试了下， 
`idea2022.1`,   latest版本的runtime下, jcef 已经不能被识别(markdown不能预览)，  不过更新到最新的pre-release的 runtime 能恢复；
在`archlinux,  fctix5.0.15, kde` 环境下  使用[fcitx5-chinese-addons输入法](https://wiki.archlinux.org/title/Fcitx5_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#:~:text=fcitx5%2Dchinese%2Daddons%20%E5%8C%85%E5%90%AB%E4%BA%86%E5%A4%A7%E9%87%8F%E4%B8%AD%E6%96%87%E8%BE%93%E5%85%A5%E6%96%B9%E5%BC%8F%EF%BC%9A%E6%8B%BC%E9%9F%B3%E3%80%81%E5%8F%8C%E6%8B%BC%E3%80%81%E4%BA%94%E7%AC%94%E6%8B%BC%E9%9F%B3%E3%80%81%E8%87%AA%E7%84%B6%E7%A0%81%E3%80%81%E4%BB%93%E9%A2%89%E3%80%81%E5%86%B0%E8%9F%BE%E5%85%A8%E6%81%AF%E3%80%81%E4%BA%8C%E7%AC%94%E7%AD%89) 在两个环境下都没有问题

**Comment by RikudouPatrickstar** [comment]
> 刚刚试了下， `idea2022.1`, latest版本的runtime下, jcef 已经不能被识别(markdown不能预览)， 不过更新到最新的pre-release的 runtime 能恢复； 在`archlinux, fctix5.0.15, kde` 环境下 使用[fcitx5-chinese-addons输入法](https://wiki.archlinux.org/title/Fcitx5_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#:~:text=fcitx5%2Dchinese%2Daddons%20%E5%8C%85%E5%90%AB%E4%BA%86%E5%A4%A7%E9%87%8F%E4%B8%AD%E6%96%87%E8%BE%93%E5%85%A5%E6%96%B9%E5%BC%8F%EF%BC%9A%E6%8B%BC%E9%9F%B3%E3%80%81%E5%8F%8C%E6%8B%BC%E3%80%81%E4%BA%94%E7%AC%94%E6%8B%BC%E9%9F%B3%E3%80%81%E8%87%AA%E7%84%B6%E7%A0%81%E3%80%81%E4%BB%93%E9%A2%89%E3%80%81%E5%86%B0%E8%9F%BE%E5%85%A8%E6%81%AF%E3%80%81%E4%BA%8C%E7%AC%94%E7%AD%89) 在两个环境下都没有问题

我也刚装了个`在manjaro, fctix5.0.15, gnome`环境，使用`fcitx5-chinese-addons输入法`，和你的描述一致。明天再试下Ubuntu

**Comment by stay-foolish-forever** [comment]
我也不太清楚，不过gnome40确实有点问题，我在gnome40上使用fcitx5的时候经常输入框乱飘（在使用gnome自带应用的时候尤其明显）
















在 2022-04-14 16:36:40，"RikudouPatrickstar" ***@***.***> 写道：

暂且怀疑是gnome4*的问题，还没仔细看。我刚刚在edge用ibus，输入框居然也在左下角

**Comment by RikudouPatrickstar** [comment]
> 我也不太清楚，不过gnome40确实有点问题，我在gnome40上使用fcitx5的时候经常输入框乱飘（在使用gnome自带应用的时候尤其明显） 在 2022-04-14 16:36:40，"RikudouPatrickstar" ***@***.***> 写道： 暂且怀疑是gnome4*的问题，还没仔细看。我刚刚在edge用ibus，输入框居然也在左下角 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

刚刚安装的`Ubuntu 21.10 impish + GNOME 40.0 + fcitx5 5.0.5-1 + fcitx5-chinese-addons 5.0.4-1` 环境，`IDEA 2022.1` `PyCharm 2022.1` 均未能复现，请更换[最新的release](https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/releases/latest)再试
