### ISSUE TITLE
Intellij IDEA 输入框位置不正确

### ISSUE THREAD

**Issue by Bryan2333** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#15]
如图
![fcitx5](https://user-images.githubusercontent.com/31512600/165324815-25875d58-f97b-41d1-bc47-238a062b4466.png)
请问一下，有什么解决方法？

**Comment by RikudouPatrickstar** [comment]
来提issue，什么信息都不提供。。。😒
你这个是显示器分辨率比较高是吧？

**Comment by Bryan2333** [comment]
> 来提issue，什么信息都不提供。。。unamused 你这个是显示器分辨率比较高是吧？

抱歉，我没提供信息是我的错。

是的，分辨了是2880x1800，我开了200%的缩放。

**Comment by RikudouPatrickstar** [comment]
https://github.com/prehonor/myJetBrainsRuntime/issues/3
上游那里，这个issue提了有一年了。大佬没理，我只是一个编译再分发产物的菜鸟，搞不定。

**Comment by szoyj** [comment]
临时方案 https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/issues/24
