### ISSUE TITLE
使用方式还不是很明白，求教下

### ISSUE THREAD

**Issue by ushaio** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#16]
使用的是idea社区版，里面的jbr目录下的文件如下
![image](https://user-images.githubusercontent.com/40263315/168961510-e9cc143b-d5ba-40fc-a697-04fa1359e70c.png)
使用说明是：直接替换 IDE 安装目录下的 jbr 目录
下载的jbr-linux-x64-2022-04-15_00-02压缩包文件如下
![image](https://user-images.githubusercontent.com/40263315/168961725-33d2c714-a8d6-49f9-844a-e0f74abce911.png)
不知道这个使用说明到底啥意思，
是让我把这个解压出来全放到jbr目录下，还是命名为jbr文件夹删除原来的jbr文件夹？？？

还有就是这个在idea 中不需要choose runtime

**Comment by RikudouPatrickstar** [comment]
你解压出问题了吧，[jbr-linux-x64-2022-04-15_00-02.zip](https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/releases/download/2022-04-15_00-02/jbr-linux-x64-2022-04-15_00-02.zip) 解压出来就是一个jbr目录，备份原jbr目录后用该目录替换
![image](https://user-images.githubusercontent.com/68163551/168967603-c2dce460-6b13-46f3-957a-57d280ca4d22.png)

**Comment by ushaio** [comment]
> 

谢谢，已解决，解压出问题了
