### ISSUE TITLE
未来会提供JBR17的构建吗？？

### ISSUE THREAD

**Issue by VariatezzZ** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#18]
在IntelliJ IDEA 2022.2 EAP的blog中提到，Jetbrains将从JBR11迁移到JBR17。
详细见该[blog](https://blog.jetbrains.com/idea/2022/05/intellij-idea-2022-2-eap-1/)。
感谢您提供的JBR。

**Comment by RikudouPatrickstar** [comment]
编译的是master分支，我可没指定11。如果patch没有问题的话，等JetBrains那边切换到17，自动编译出来的就是17。~~如果patch有问题的话，这个编译项目就没了~~

**Comment by VariatezzZ** [comment]
> 编译的是master分支，我可没指定11。如果patch没有问题的话，等JetBrains那边切换到17，自动编译出来的就是17。~如果patch有问题的话，这个编译项目就没了~

OK,感谢回复。

**Comment by VariatezzZ** [comment]
> 编译的是master分支，我可没指定11。如果patch没有问题的话，等JetBrains那边切换到17，自动编译出来的就是17。~如果patch有问题的话，这个编译项目就没了~

如果要编译17的话，actions的boot jdk版本记得要改噢。

**Comment by VariatezzZ** [comment]
17我编译没成功(添加patch的构建是失败的)，不添加patch但是加jcef的模块构建成功，用的是[JB仓库](https://github.com/JetBrains/JetBrainsRuntime)的master17分支。

**Comment by VariatezzZ** [comment]
> 编译的是master分支，我可没指定11。如果patch没有问题的话，等JetBrains那边切换到17，自动编译出来的就是17。~如果patch有问题的话，这个编译项目就没了~

17我编译没成功(添加patch的构建是失败的)，不添加patch但是加jcef的模块构建成功，用的是[JB仓库](https://github.com/JetBrains/JetBrainsRuntime)的master17分支。

**Comment by RikudouPatrickstar** [comment]
fcitx输入法候选框不跟随光标的问题，直接提交issue叫JetBrains去修吧。我这里也只是编译，patch都是别人的。而且这个patch依然存在问题，比如IDE的Terminal里面还是会不跟随。

**Comment by VariatezzZ** [comment]
> fcitx输入法候选框不跟随光标的问题，直接提交issue叫JetBrains去修吧。我这里也只是编译，patch都是别人的。而且这个patch依然存在问题，比如IDE的Terminal里面还是会不跟随。

唉，没用的，这个问题七年前就提交给JB了，但JB到现在都没管。

**Comment by RikudouPatrickstar** [comment]
哈哈，所以我已经放弃在Linux桌面环境做开发以及日常使用很久了，太折腾了

**Comment by VariatezzZ** [comment]
> 哈哈，所以我已经放弃在Linux桌面环境做开发以及日常使用很久了，太折腾了

哦不，说错了，九年前就提交的问题，[见此](https://youtrack.jetbrains.com/issue/JBR-2460)
linux桌面端就凑合着用吧。。。唉

**Comment by VariatezzZ** [comment]
> 哈哈，所以我已

**Comment by huyz-git** [comment]
> > 编译的是master分支，我可没指定11。如果patch没有问题的话，等JetBrains那边切换到17，自动编译出来的就是17。~如果patch有问题的话，这个编译项目就没了~
> 
> 17我编译没成功(添加patch的构建是失败的)，不添加patch但是加jcef的模块构建成功，用的是[JB仓库](https://github.com/JetBrains/JetBrainsRuntime)的master17分支。

原版的 patch 是没法用在 jbr17 上
要用 jbr17 可以用这里的 patch：https://aur.archlinux.org/packages/jre17-jetbrains-imfix
这里的 patch 是 archlinuxcn 社区里的一位用户 （ https://github.com/edward-p ） 针对 jbr17 修改的

另外需要注意一点，jbr 仓库里的 jbr17 的 release tag 是有问题的，如果想编译特定版本的 jbr17，不能用 release 里的 tag，需要转换一下：如，release 里的 tar 是 jbr17.0.3b463.3，那么对应的源码的 tag 是 jb17.0.3-b463.3 （ 少个 r，多个 - ）。

**Comment by VariatezzZ** [comment]
> 

是的我注意到了，一开始用的release的tag，编译出的是11

**Comment by VariatezzZ** [comment]
> 

是的我注意到了，一开始用的release的tag，编译出的是11
感谢
