### ISSUE TITLE
在clion2019.2上应用后ide方向键不能用且无法切换出中文输入法

### ISSUE THREAD

**Issue by a0002liu** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#2]
是不是对ide版本有要求？换了jre后方向键都不起作用了。我操作系统是Ubuntu18.04

**Comment by RikudouPatrickstar** [comment]
可能吧，你换新一点的版本试试，我只在 2020 年及之后的 IDE 上面使用过。Ubuntu 上面我都有正常使用过这个 JBR 的，不过当时是 18.04 还是 20.04 就不记得了。
