### ISSUE TITLE
求助，球球了

### ISSUE THREAD

**Issue by Misaki030112** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#20]
是这样，
系统：Ubuntu 22.04

我一开始的时候使用了ibus 输入法，IDEA运行一切正常，文字候选框可以正常的跟随光标，但是我安装切换了fcitx输入法
，之后又 卸载了 fcitx 输入法之后，再去使用 ibus 在IDEA 里面出现了文字候选框始终在，左下角的情况

我确定我的环境变量全部设的是ibus，自启动项也删除了。

使用这个项目的jbr 替换还是无效  ， 已经很苦恼很苦恼 = = 
![图片](https://user-images.githubusercontent.com/82640066/169951461-ffdb7787-32b9-4dd4-b8cc-ce993a354856.png)

**Comment by RikudouPatrickstar** [comment]
不会，帮不了你，这个项目不是针对ibus的。我记得前段时间装 Ubuntu 22.04 gnome 版本的时候，ibus就是在左下角啊🙈。

**Comment by Misaki030112** [comment]
已经解决了，删除ibus,拥抱fcitx
