### ISSUE TITLE
master得改成main了

### ISSUE THREAD

**Issue by szoyj** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#25]
保险期间改成main吧
https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/blob/9f6927487ba1af70bbdfb0fcc1cb6078ef6565ad/.github/workflows/jbr-linux-x64.yml#L68

根据下面commit的readme信息，圣母们好像要改用main了
https://github.com/JetBrains/JetBrainsRuntime/commit/095f376e49abb4cd295540d97f8a298157feb885

**Comment by RikudouPatrickstar** [comment]
拉master应该也不会出现拉不了的问题吧。拒绝修改，master不master的关我屁事，我又没奴役过黑人，凭啥我要花时间给黑人改代码。圣母婊爱用不用，暴躁派大星在线打人

**Comment by szoyj** [comment]
@RikudouPatrickstar master上的最后一次提交是6月1号，你不改不行。。。

**Comment by RikudouPatrickstar** [comment]
wctmd，直接换了个分支，还以为是重命名的。。。。行吧
