### ISSUE TITLE
搜狗输入法在IDEA2022.2中出现的bug

### ISSUE THREAD

**Issue by Free-Aaron-Li** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#29]
IDEA2022.2bug
当在idea中使用termial时，输入中文，搜狗输入法会显示在头顶。
具体表现：
![image](https://user-images.githubusercontent.com/95997167/183667995-e5221228-b8ee-48f9-8063-c0954715afc1.png)
IDEA版本：
![image](https://user-images.githubusercontent.com/95997167/183668156-cae041c1-f154-451b-8552-7cbb7352d708.png)
搜狗输入法版本：
![image](https://user-images.githubusercontent.com/95997167/183668342-73390c0d-99b9-49f1-975e-f278179378d7.png)

**Comment by RikudouPatrickstar** [comment]
老问题了，没办法
