### ISSUE TITLE
最新版本idea2022.3EAP 在IDE无法选择最新的jbr，选择后会报错

### ISSUE THREAD

**Issue by gerryhjs** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#31]
推测报错应该是有某些.so库存在问题

**Comment by gerryhjs** [comment]
![截图_jetbrains-pycharm_20220926100233](https://user-images.githubusercontent.com/45413498/192179661-f0df43ce-b3cd-4bc0-a630-172342de0af3.png)

**Comment by RikudouPatrickstar** [comment]
尝试直接替换jbr目录呢

**Comment by gerryhjs** [comment]
Error: failed /home/hjs/Downloads/jbr_jcef-17.0.4-x64-b469/lib/server/libjvm.so, because /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/hjs/Downloads/jbr_jcef-17.0.4-x64-b469/lib/server/libjvm.so)

**Comment by gerryhjs** [comment]
@RikudouPatrickstar 直接替换后启动报错如上

**Comment by gerryhjs** [comment]
我尝试把官方jbr的lib文件夹替换到修改后的jbr后可以启动，但是光标位置还是错的

**Comment by RikudouPatrickstar** [comment]
@gerryhjs 直接替换后，怎么报错的路径还是你原来的路径？

**Comment by gerryhjs** [comment]
@RikudouPatrickstar 这个错误是我后面强制调过jbr校验之后设置成功再启动IDE报的错，直接替换报错相同。选择IDE校验那边有办法可以跳过检查，先选择一个正常IDE的路径作为运行时，然后把jbr替换到对应路径下即可。

**Comment by gerryhjs** [comment]
另外2022.3官方已经放弃对JBR11的支持了，我尝试使用上一个版本的jbr，启动报错提示java版本过低。

**Comment by yuanphoenix** [comment]
可能是你系统的问题，缺少一个so文件。你可以将楼主的jbr-linux-x64.yml里的 runs-on: ubuntu-20.04换成    runs-on: ubuntu-18.04试试。

**Comment by gerryhjs** [comment]
@yuanphoenix 嗯应该是我这边缺库的问题，感谢
