### ISSUE TITLE
deepin下无法启动

### ISSUE THREAD

**Issue by aohanhongzhi** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#36]
![image](https://user-images.githubusercontent.com/37319319/211145192-9d8f933e-93b0-4d4a-93fb-67541e36c1e7.png)

但是从oracle官网下载的jdk17和19都是正常的。

https://www.oracle.com/java/technologies/downloads/#java17

![image](https://user-images.githubusercontent.com/37319319/211145220-11db73c2-353d-4cd2-9e68-03fa76b38be5.png)

**Comment by Rurikou** [comment]
> ![image](https://user-images.githubusercontent.com/37319319/211145192-9d8f933e-93b0-4d4a-93fb-67541e36c1e7.png)
> 
> 但是从oracle官网下载的jdk17和19都是正常的。
> 
> https://www.oracle.com/java/technologies/downloads/#java17
> 
> ![image](https://user-images.githubusercontent.com/37319319/211145220-11db73c2-353d-4cd2-9e68-03fa76b38be5.png)

兄弟，我也这样，千万不要换glibc2.29，不然系统直接崩了，我刚回滚过来。
https://github.com/ayanamist/JetBrainsRuntime-for-fcitx
用他的库说我需要安装相关组件，我还在研究中，哈哈
![image](https://user-images.githubusercontent.com/23163316/211145511-e02007fa-be2c-49e2-8384-674c4e114377.png)

**Comment by aohanhongzhi** [comment]
> > ![image](https://user-images.githubusercontent.com/37319319/211145192-9d8f933e-93b0-4d4a-93fb-67541e36c1e7.png)
> > 但是从oracle官网下载的jdk17和19都是正常的。
> > https://www.oracle.com/java/technologies/downloads/#java17
> > ![image](https://user-images.githubusercontent.com/37319319/211145220-11db73c2-353d-4cd2-9e68-03fa76b38be5.png)
> 
> 兄弟，我也这样，千万不要换glibc2.29，不然系统直接崩了，我刚回滚过来。 https://github.com/ayanamist/JetBrainsRuntime-for-fcitx 用他的库说我需要安装相关组件，我还在研究中，哈哈 ![image](https://user-images.githubusercontent.com/23163316/211145511-e02007fa-be2c-49e2-8384-674c4e114377.png)

早已经重装了，第一次机缘巧合的安装上了glibc2.29，然后系统挂了。现在也不指望再装glibc了，要么等着deepin解决，要么等着这个库大佬解决把。重装后都没有咋用deepin了，直接转Ubuntu了。

**Comment by aohanhongzhi** [comment]
> > ![image](https://user-images.githubusercontent.com/37319319/211145192-9d8f933e-93b0-4d4a-93fb-67541e36c1e7.png)
> > 但是从oracle官网下载的jdk17和19都是正常的。
> > https://www.oracle.com/java/technologies/downloads/#java17
> > ![image](https://user-images.githubusercontent.com/37319319/211145220-11db73c2-353d-4cd2-9e68-03fa76b38be5.png)
> 
> 兄弟，我也这样，千万不要换glibc2.29，不然系统直接崩了，我刚回滚过来。 https://github.com/ayanamist/JetBrainsRuntime-for-fcitx 用他的库说我需要安装相关组件，我还在研究中，哈哈 ![image](https://user-images.githubusercontent.com/23163316/211145511-e02007fa-be2c-49e2-8384-674c4e114377.png)

说实话，这问题应该像jetbrain反馈下，关注jetbrain的公众号，直接反馈，有回应的，但是用户太少优先级不高。bug都十几年了

**Comment by bluesky9922** [comment]
deepin请使用20211030这个或之前的版本，后面的版本编译设备的glibc升级了，所以deepin使用不了

**Comment by aohanhongzhi** [comment]
> deepin请使用20211030这个或之前的版本，后面的版本编译设备的glibc升级了，所以deepin使用不了

我想要jdk17啊，那只能放弃deepin了。

**Comment by aohanhongzhi** [comment]
> deepin请使用20211030这个或之前的版本，后面的版本编译设备的glibc升级了，所以deepin使用不了

我想要jdk17啊，那只能放弃deepin了。

**Comment by bluesky9922** [comment]
> > deepin请使用20211030这个或之前的版本，后面的版本编译设备的glibc升级了，所以deepin使用不了
> 
> 我想要jdk17啊，那只能放弃deepin了。

唉，我终于看到了jb官方修复通知了，预计近期修复输入法问题，尼玛泪目，就像linuxqq3.0一样

**Comment by Powerful24HS** [comment]
> > > deepin请使用20211030这个或之前的版本，后面的版本编译设备的glibc升级了，所以deepin使用不了
> > 
> > 
> > 我想要jdk17啊，那只能放弃deepin了。
> 
> 唉，我终于看到了jb官方修复通知了，预计近期修复输入法问题，尼玛泪目，就像linuxqq3.0一样

看到qq3.0我忍不住笑了。输入法不跟随已经是2016年就遇到过的陈年老bug了，官方终于想起了修复了。
不过2023年2月18日，最新的idea 2022.3.2，还没有修复。

**Comment by bluesky9922** [comment]
> > > > deepin请使用20211030这个或之前的版本，后面的版本编译设备的glibc升级了，所以deepin使用不了
> > > 
> > > 
> > > 我想要jdk17啊，那只能放弃deepin了。
> > 
> > 
> > 唉，我终于看到了jb官方修复通知了，预计近期修复输入法问题，尼玛泪目，就像linuxqq3.0一样
> 
> 看到qq3.0我忍不住笑了。输入法不跟随已经是2016年就遇到过的陈年老bug了，官方终于想起了修复了。 不过2023年2月18日，最新的idea 2022.3.2，还没有修复。

快了，下个版本就修（2023.1）。
https://youtrack.jetbrains.com/issue/JBR-2460/Wrong-position-of-input-window-and-no-input-preview-with-fcitx-and-ubuntu-13.04
这个是jb官方的issue，这个已经问题提出9年了，终于要修了，很快就不再需要补丁了

**Comment by yuanphoenix** [comment]
deepin 无法启动的，可以试试我打包的这个。
https://github.com/yuanphoenix/JetBrainsRuntime-for-Linux-x64/releases/tag/jbr-release-17.0.5b653.14
原因：楼主用的ubuntu20打包的，deepin的glibc太旧用不了，换成ubuntu18打包就好了。

**Comment by aohanhongzhi** [comment]
最新的jbr-17.0.6可以在deepin20.8上运行了。
![image](https://user-images.githubusercontent.com/37319319/229263286-842eb3c5-8587-4fb7-ae49-d117a33f2df8.png)
