### ISSUE TITLE
Arch Linux 下无法输入中文。

### ISSUE THREAD

**Issue by Misaki030112** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#37]
使用的是 Arch Linux，使用jbr已经替换了
选字框正常
无法输入中文
fcitx5 + 搜狗输入法

![image](https://user-images.githubusercontent.com/82640066/222879713-dbe57af4-eca3-47f5-8b43-c61b16123f20.png)

**Comment by wujimin** [comment]
```
# 不设置这个，intellij全家桶中，中文无法上屏。但是gedit之类的程序可以正常使用
echo 'export LC_ALL=C.utf-8' >> /etc/profile
```

**Comment by Misaki030112** [comment]
> ```
> # 不设置这个，intellij全家桶中，中文无法上屏。但是gedit之类的程序可以正常使用
> echo 'export LC_ALL=C.utf-8' >> /etc/profile
> ```

非常感谢您

**Comment by xuexiansen123** [comment]
你好，请问下 arm 的可以使用哪个 jbr 包替换呐？直接使用 x86 的嘛？多多感谢！ @Misaki030112
