### ISSUE TITLE
双屏下无法移动pycharm窗口位置受阻

### ISSUE THREAD

**Issue by tongchangD** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#39]
采用最近版本的进行替换，但是在双屏下，移动pycharm窗口位置会受阻，移动不了，时常会留在原地，不知为何

**Comment by wujimin** [comment]
用的WSLg吧，换成mobaXterm就没这个问题了

**Comment by wujimin** [comment]
### 为何不使用`WSLg`的显示服务

`WSLg`本身支持直接运行linux的GUI app  
但是本方案中，仍然选择了额外运行`x server`

这是因为，到`2023/3/30`为止，通过`WSLg`显示界面，至少有以下问题：

* 多显示器场景下，窗口通过快捷键移动到其他显示器后，会立即跳回来
* 为输入法设置快捷键时，可选的余地更小
* JetBrains全家桶，都会有一个大大的标题栏，以及一个宽宽的窗口边框，使用体验很差

**Comment by tongchangD** [comment]
> 用的WSLg吧，换成mobaXterm就没这个问题了

请问是如何更换mobaXterm 这个，我对这个gui有些懵

**Comment by wujimin** [comment]
1. 下载mobaXterm，启动它
2. wsl里执行：
```
WSL_WINDOWS_HOST=$(grep nameserver /etc/resolv.conf | cut -d ' ' -f 2)
# 如果使用win11的wslg，那么这里应该设置为：export DISPLAY=:0
export DISPLAY=${WSL_WINDOWS_HOST}:0
```
3. 再启动ide即可

**Comment by tongchangD** [comment]
> 1. 下载mobaXterm，启动它
> 2. wsl里执行：
> 
> ```
> WSL_WINDOWS_HOST=$(grep nameserver /etc/resolv.conf | cut -d ' ' -f 2)
> # 如果使用win11的wslg，那么这里应该设置为：export DISPLAY=:0
> export DISPLAY=${WSL_WINDOWS_HOST}:0
> ```
> 
> 3. 再启动ide即可

thanks
