### ISSUE TITLE
新版本 似乎不再使用javaFX,  用JCEF代替,  导致markdown文档不能预览

### ISSUE THREAD

**Issue by Voghost** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#4]
1. 新版markdown还是 不能使用,   似乎是使用了 JCEF 代替 javafx
2. 参考: 
    a.  [https://blog.jetbrains.com/platform/2020/07/javafx-and-jcef-in-the-intellij-platform/](https://blog.jetbrains.com/platform/2020/07/javafx-and-jcef-in-the-intellij-platform/)
    b.   [https://plugins.jetbrains.com/docs/intellij/jcef.html](https://plugins.jetbrains.com/docs/intellij/jcef.html)
    c.  [https://github.com/JetBrains/JetBrainsRuntime/blob/master/jb/project/tools/linux/scripts/mkimages_x64.sh](https://github.com/JetBrains/JetBrainsRuntime/blob/master/jb/project/tools/linux/scripts/mkimages_x64.sh#L8)

**Comment by RikudouPatrickstar** [comment]
已添加 JCEF，请下载测试并及时反馈结果

https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/releases/download/202110250050/jbr-linux-x64-202110250050.zip

**Comment by Voghost** [comment]
> 已添加 JCEF，请下载测试并及时反馈结果
> 
> https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/releases/download/202110250050/jbr-linux-x64-202110250050.zip

似乎没有成功整合JCEF， 有用到的JCEF的插件报错没有jcef
![Screenshot_20211025_135942](https://user-images.githubusercontent.com/49421354/138642375-31ebc7e5-32cc-4824-974e-ce206d8ebfb1.png)

**Comment by RikudouPatrickstar** [comment]
估计是要 jlink，不过我不熟悉这个东西，刚刚尝试改了几次都出问题了。最近太忙了，如果你能弄的话，欢迎 pr，感谢！

**Comment by Voghost** [comment]
这个我也不太懂,  我尝试过在ubuntu虚拟机中添加jcef都失败了， 不过也十分感谢了

**Comment by RikudouPatrickstar** [comment]
帮我试下最新的 pre-release，这回应该弄好了，从中午搞到刚刚。。。

https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/releases/tag/202110301849

**Comment by Voghost** [comment]
> 帮我试下最新的 pre-release，这回应该弄好了，从中午搞到刚刚。。。
> 
> https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/releases/tag/202110301849

好了！，十分感谢， 辛苦了，辛苦了！  
![Screenshot_20211030_195055](https://user-images.githubusercontent.com/49421354/139531742-0a47ef0f-060e-4ce0-a467-b583a619e6c2.png)

**Comment by RikudouPatrickstar** [comment]
OK，可算弄好了😂。
感谢你提供解决思路以及帮忙测试。

忍不住吐槽一下 JetBrains，放个脚本在那里也不说明下怎么用，其中两个路径相关的环境变量试了一下午才试出来。JCEF 也是他们修改的版本而不是官方的，还好看到了他们自己有一个。。。
