### ISSUE TITLE
更换jbr后，idea的标题栏与系统标题栏分开了

### ISSUE THREAD

**Issue by wangxiaoyan369** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#47]
![image](https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/assets/39553149/efcca609-8659-4749-908e-2d0497abe93c)

idea版本：2023.2.2 UE
jbr版本：jbr_jcef-17.0.6-linux-x64-b829.5.tar.gz
linux版本：ubuntu22.04

**Comment by AlanSune** [comment]
进入配置 `Appearance & Behavior → Appearance`，然后勾选以下选项，保存重启即可。
![screenshot-20230927-164001](https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/assets/19259263/3e1d5450-ae64-46c4-b061-335035897aba)

**Comment by Bryan2333** [comment]
我觉得应该是你的jbr版本太低了，还有官方已经正式修复这个问题了。

https://youtrack.jetbrains.com/issue/JBR-2460/Wrong-position-of-input-window-and-no-input-preview-with-fcitx-and-ubuntu-13.04#focus=Comments-27-8112829.0-0

**Comment by wangxiaoyan369** [comment]
> 进入配置 `Appearance & Behavior → Appearance`，然后勾选以下选项，保存重启即可。 ![screenshot-20230927-164001](https://user-images.githubusercontent.com/19259263/270918370-3e1d5450-ae64-46c4-b061-335035897aba.png)

不行，似乎这个控制的不是系统标题栏，而是软件内的菜单栏
![image](https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/assets/39553149/0c40c6e0-35c2-456a-8328-1f1cfca3ab1f)

**Comment by wangxiaoyan369** [comment]
> 进入配置 `Appearance & Behavior → Appearance`，然后勾选以下选项，保存重启即可。 ![screenshot-20230927-164001](https://user-images.githubusercontent.com/19259263/270918370-3e1d5450-ae64-46c4-b061-335035897aba.png)

显示不支持
![image](https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/assets/39553149/2a218f16-df83-48e1-8048-c53247748449)

官方jbr是可以的
![image](https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/assets/39553149/2bcf8d1a-b904-4d2f-85c2-6c8d56864ef7)

**Comment by AlanSune** [comment]
@wangxiaoyan369 你用的jdk版本太低了，所以不支持，你下载新的版本就支持这个配置。以下的渠道可以获取新的jdk：
- 我fock的修复版本：https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/releases
- 官方修复版本：https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-17.0.8.1-linux-x64-b1000.39.tar.gz
    - 官方相关链接：https://youtrack.jetbrains.com/issue/JBR-2460/Wrong-position-of-input-window-and-no-input-preview-with-fcitx-and-ubuntu-13.04

**Comment by wangxiaoyan369** [comment]
> @wangxiaoyan369 你用的jdk版本太低了，所以不支持，你下载新的版本就支持这个配置。以下的渠道可以获取新的jdk：
> 
> * 我fock的修复版本：https://github.com/AlanSune/JetBrainsRuntime-for-Linux-x64/releases
> * 官方修复版本：https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-17.0.8.1-linux-x64-b1000.39.tar.gz
>   
>   * 官方相关链接：https://youtrack.jetbrains.com/issue/JBR-2460/Wrong-position-of-input-window-and-no-input-preview-with-fcitx-and-ubuntu-13.04

有效，感谢
