### ISSUE TITLE
我这边下载最新的包替换后fcitx还是光标不跟随

### ISSUE THREAD

**Issue by kerojiang** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#5]
下载了最新的三个版本jbr-linux-x64-202110250050，jbr-linux-x64-202110011042，jbr-linux-x64-202109011042
在rider和goland里面fcitx都光标无法跟随
fcitx版本：5.0.9-1
linux版本:Linux 5.14.10-1-MANJARO 
gnome：40.4
是只有我有这个问题吗？ 我看都没人反馈

**Comment by RikudouPatrickstar** [comment]
确定是正确替换了 jbr 目录吗？我以前在 manjaro 上是用过这个的，不过 gnome 没这么新，不知道 gnome 版本有没有原因。（我自己好久都不用 Linux 桌面环境了）

**Comment by RikudouPatrickstar** [comment]
试下最新的 release

**Comment by kerojiang** [comment]
用了jbr-linux-x64-202110301849版本，markdown预览没问题，但是光标还是不跟随，一直在左下角
goland 2021.2.4
我是直接删了原来的jbr,用下载的替换进去，之前也一直是这样弄

**Comment by Voghost** [comment]
> 用了jbr-linux-x64-202110301849版本，markdown预览没问题，但是光标还是不跟随，一直在左下角 goland 2021.2.4 我是直接删了原来的jbr,用下载的替换进去，之前也一直是这样弄

试试choose runtime这个插件， 我用这个插件能正常使用
![Screenshot_20211030_204505](https://user-images.githubusercontent.com/49421354/139533359-7eab2df6-cf0d-424d-87be-e182b6be4d49.png)


安装后 double shift  输入插件名字  就能切换指定 runtime

**Comment by kerojiang** [comment]
![截屏-20211102144332-708x474](https://user-images.githubusercontent.com/5567031/139798646-d5c2520c-c8ae-4edd-97a0-4cc2f700b924.png
![截屏-20211102144308-1179x435](https://user-images.githubusercontent.com/5567031/139798669-458b3bc0-b238-414a-a5d6-b23cd0afb53e.png)
![截屏-20211102144237-1192x984](https://user-images.githubusercontent.com/5567031/139798678-5152bb88-f21b-480f-b869-6d972353e0f0.png)
)
还是不行,jbr-linux是我下载最新的版本，已经用choose runtime选择了,但是在fcitx的时候输入框还是在左下角，没有光标跟随

**Comment by kerojiang** [comment]
vscode下是完全正常的
![截屏-20211102144657-826x671](https://user-images.githubusercontent.com/5567031/139798947-3ed39afb-bcc9-4626-a3da-8efeabe4c6db.png)
用dbeaver也是光标正常跟随的

**Comment by kerojiang** [comment]
找到原因了,是因为fcitx引起的,fcitx有一个选项UseOnTheSpot=False，这里要设置成False就能正常光标跟随了，我之前是True就一直不行

**Comment by aohanhongzhi** [comment]
UseOnTheSpot=False 截个图啊。找不到位置。 @kerojiang

**Comment by aohanhongzhi** [comment]
搞定了！感谢。
https://bbs.deepin.org/post/228824?id=228824&type_id=111&forum_name=Experiences%20and%20Insight
@kerojiang
