### ISSUE TITLE
替换jbr后出现一个小问题

### ISSUE THREAD

**Issue by tracker93** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#7]
快捷键Ctrl+Alt+鼠标左键 跳转到另一个java文件的实现方法后，
无法使用Ctrl+D复制行，输入错误的内容也无法使用Delete删除，
需要切换到其他打开的文件再切换回来，快捷键和Delete才恢复正常

**Comment by ayanamist** [comment]
我也有这个问题，后面两个pre-release jbr-linux-x64-2021-12-01_08-58 jbr-linux-x64-2022-01-05_14-26 都有这个问题，但在 jbr-linux-x64-202110301849 是正常的。

看起来应该是 #10 里提到的问题。

**Comment by RikudouPatrickstar** [comment]
刚装的 Ubuntu 21.10 gnome fcitx5 无法复现，你们用的什么环境？

**Comment by ayanamist** [comment]
> 刚装的 Ubuntu 21.10 gnome fcitx5 无法复现，你们用的什么环境？

Ubuntu 20.04没有额外安装+fcitx4

**Comment by stay-foolish-forever** [comment]
> 

想知道Ubuntu21.10应该如何配置fcitx5，我在Ubuntu21.10上替换jbr后IDEA的光标还是不跟随

**Comment by RikudouPatrickstar** [comment]
已合并 #10 ，请更换[最新的release](https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64/releases/latest)，看问题是否仍然存在
