### ISSUE TITLE
请问能否编译一个jdk8版本

### ISSUE THREAD

**Issue by Conanzhou** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#8]
fcitx 输入法候选框不跟随光标的问题在matlab和mathematica中同样出现，使用编译的jbr11能解决光标跟随问题，但是会有其他报错

**Comment by RikudouPatrickstar** [comment]
建议自行根据 Matlab Mathematica 官方给的环境去做相关修改并编译，JetBrainsRuntime 是给 JetBrains 系列 IDE 用的
