### ISSUE TITLE
could not initialize class com.github.dockerjava.okhttp.NamedPipeSocket$Kernel32

### ISSUE THREAD

**Issue by edwinhuish** [RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64#9]
出现如下问题：
![image](https://user-images.githubusercontent.com/5207925/147654311-ce10e2b6-cdf3-4dfc-9e90-902989cb720d.png)

**Comment by edwinhuish** [comment]
![image](https://user-images.githubusercontent.com/5207925/147654687-1fbc3e4a-bccc-4b0d-b427-ed625943696a.png)

**Comment by RikudouPatrickstar** [comment]
这问题是替换jbr之后出现的？

**Comment by edwinhuish** [comment]
> 这问题是替换jbr之后出现的？

是的，不过已经太久了，我已经不用Linux的jetbrains了

**Comment by RikudouPatrickstar** [comment]
哈哈，其实更早以前我就已经不用了Linux桌面环境了，都是今天看到issue有几个了，装了环境来看下问题
